import type { Metadata } from 'next'
import { SanityLive } from '@/sanity/lib/live'
import { ClerkProvider } from '@clerk/nextjs'
import ThemeProvider from '@/components/ThemeProvider'
import { SidebarProvider } from '@/components/providers/SidebarProvider'

export const metadata: Metadata = {
	title: 'Dashboard',
	description: 'Generated by create next app'
}

export default function DashboardLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<ClerkProvider>
			<ThemeProvider
				attribute="class"
				defaultTheme="system"
				enableSystem
				disableTransitionOnChange
			>
				<SidebarProvider>
					<div className="h-full">{children}</div>
				</SidebarProvider>
			</ThemeProvider>

			<SanityLive />
		</ClerkProvider>
	)
}
