import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import Header from '@/components/Header'
import { SanityLive } from '@/sanity/lib/live'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function UserLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider>
			<div className="min-h-screen flex flex-col">
				<main className="flex-1">
					{/* Header */}
					<Header />
					{children}
				</main>
			</div>

			{/* Add Sanity Live for Live to get live data from sanity to the pages */}
			<SanityLive />
		</ClerkProvider>
	)
}
